services:
  hassil.api:
    image: dhi.io/postgres:18-debian13-dev
    container_name: hassil-api-postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'

