import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import type { Invoice } from '../types'
import { formatCurrency, formatDate } from '../utils/formatters'
import { useInvoices } from '../hooks'
import PageHeading from '../components/PageHeading'
import StatusBadge from '../components/StatusBadge'
import DetailGrid from '../components/DetailGrid'
import DisclosurePanel from '../components/DisclosurePanel'
import Breadcrumbs from '../components/Breadcrumbs'

export default function InvoiceDetail() {
    const { id } = useParams<{ id: string }>()
    const navigate = useNavigate()
    const { get: getInvoice } = useInvoices()
    const [invoice, setInvoice] = useState<Invoice | null>(null)
    const [actionError, setActionError] = useState('')

    useEffect(() => {
        let active = true

        const load = async () => {
            if (!id) return

            try {
                const res = await getInvoice(id)
                if (active) setInvoice(res ?? null)
            } catch (err: any) {
                if (active) setActionError(err.message || 'Could not load invoice.')
            }
        }

        load()

        return () => {
            active = false
        }
    }, [id, getInvoice])

    if (!invoice) {
        return (
            <div className="card">
                <h2 className="card-title">Invoice not found</h2>
                <p className="soft-text mt-8">The selected invoice does not exist.</p>
                {actionError && <div className="feedback-item error mt-16">{actionError}</div>}
                <button className="btn btn-primary mt-16" onClick={() => navigate('/invoices')}>Back to invoices</button>
            </div>
        )
    }



    return (
        <>
            <Breadcrumbs items={[{ label: 'Invoices', onClick: () => navigate('/invoices') }, { label: invoice.invoiceNumber }]} />
            <PageHeading title="Invoice details" description={`${invoice.invoiceNumber} · ${invoice.client.name}`} />
            <div className="card">
                    <div className="card-header">
                        <h2 className="card-title">Summary</h2>
                        <StatusBadge status={invoice.status} />
                    </div>
                    <DetailGrid
                        items={[
                            ['Client', `${invoice.client.name} · ${invoice.client.email}`],
                            ['Amount', formatCurrency(invoice.amount, invoice.currency)],
                            ['Due date', formatDate(invoice.dueDate)],
                            ['Payment terms', invoice.paymentTerms || 'Not specified'],
                        ]}
                    />
                    <DisclosurePanel title="More invoice details">
                        <DetailGrid
                            items={[
                                ['Issue date', formatDate(invoice.issueDate)],
                                ['Receivable source', invoice.receivableSource === 'DirectClientInvoice' ? 'Direct client invoice' : 'Freelance platform payout'],
                                ['Description', invoice.description || 'No description'],
                                ['Fingerprint', invoice.fingerprint || 'Generated by Hassil'],
                            ]}
                        />
                    </DisclosurePanel>
                    {actionError && <div className="feedback-item error mt-16">{actionError}</div>}
                    {/*<div className="mock-upload mt-18">*/}
                        {/*<div className="space-between">*/}
                        {/*    <h3>Optional evidence ({invoice.documents.length} file{invoice.documents.length !== 1 ? 's' : ''})</h3>*/}
                        {/*</div>*/}
                        {/*{invoice.documents.map((doc) => (*/}
                        {/*    <div key={doc.id} className="detail-item mt-8">*/}
                        {/*        <span>{doc.documentType}</span>*/}
                        {/*        <strong>{doc.fileName}</strong>*/}
                        {/*    </div>*/}
                        {/*))}*/}
                        {/*<button className="btn btn-secondary full-width mt-12" onClick={addDocument} disabled={actionLoading}>*/}
                        {/*    <Icon name="plus" /> {actionLoading ? 'Adding...' : 'Add optional evidence'}*/}
                        {/*</button>*/}
                    {/*</div>*/}
                </div>
                {/*<div className="card card-gold">*/}
                {/*    <h2 className="card-title">Advance option</h2>*/}
                {/*    <div className={`invoice-detail-next-action ${nextAction.tone}`}>*/}
                {/*        <span>Next action</span>*/}
                {/*        <strong>{nextAction.title}</strong>*/}
                {/*        <p>{nextAction.hint}</p>*/}
                {/*        <button*/}
                {/*            className={`btn ${nextAction.tone === 'primary' ? 'btn-primary' : 'btn-secondary'} full-width mt-12`}*/}
                {/*            onClick={nextAction.onClick}*/}
                {/*            disabled={nextAction.disabled}*/}
                {/*        >*/}
                {/*            <Icon name={nextAction.icon} /> {nextAction.label}*/}
                {/*        </button>*/}
                {/*    </div>*/}
                {/*    {quote ? (*/}
                {/*        <>*/}
                {/*            <ModelBadge model={quote.financingModel} />*/}
                {/*            <p className="soft-text mt-12">*/}
                {/*                {quote.financingModel === 'InvoiceFactoring'*/}
                {/*                    ? 'Client confirms the invoice and pays Hassil on the due date.'*/}
                {/*                    : 'Client is not notified. Repayment happens after client payment is received.'}*/}
                {/*            </p>*/}
                {/*            <DetailGrid*/}
                {/*                items={[*/}
                {/*                    ['Advance amount', formatCurrency(quote.advanceAmount, invoice.currency)],*/}
                {/*                    ['Flat fee', formatCurrency(quote.feeAmount, invoice.currency)],*/}
                {/*                    ['Requested percent', `${(quote.requestedPercent * 100).toFixed(0)}%`],*/}
                {/*                    ['Eligibility', quote.isEligible ? 'Eligible' : 'Needs attention'],*/}
                {/*                ]}*/}
                {/*            />*/}
                {/*        </>*/}
                {/*    ) : (*/}
                {/*        <p className="soft-text mt-12">*/}
                {/*            {quoteLoading ? 'Loading backend quote...' : 'Advance quote is not available for this invoice state.'}*/}
                {/*        </p>*/}
                {/*    )}*/}
                {/*    <VerificationChecklist invoice={invoice} quote={quote} />*/}
                {/*    {quoteError && <div className="feedback-item warning mt-16">{quoteError}</div>}*/}
                {/*    /!*{quote?.eligibilityMessages.length ? (*!/*/}
                {/*    /!*    <div className="risk-flags mt-16">*!/*/}
                {/*    /!*        {quote.eligibilityMessages.map((message) => (*!/*/}
                {/*    /!*            <div key={message} className="risk-flag-item">{message}</div>*!/*/}
                {/*    /!*        ))}*!/*/}
                {/*    /!*    </div>*!/*/}
                {/*    /!*) : null}*!/*/}
                {/*</div>*/}
        </>
    )
}
