import type { AppState, AdvanceRequest, Client, Invoice, Transaction, TrustScoreEvent, User } from './types';
import { buildAiSnapshot, createFingerprint } from './utils';

const now = new Date('2026-04-28T09:00:00+03:00').toISOString();

const clients: Client[] = [
  { id: 'client-omar', name: 'Omar Hospitality Group', email: 'ap@omarhospitality.ae', country: 'UAE' },
  { id: 'client-noura', name: 'Noura Retail Group', email: 'ap@nouraretail.sa', country: 'Saudi Arabia' },
  { id: 'client-platform', name: 'Nabd Freelance Marketplace', email: 'payouts@nabdwork.com', country: 'UAE' },
  { id: 'client-lynx', name: 'Lynx Digital', email: 'finance@lynxdigital.qa', country: 'Qatar' },
];

const users: User[] = [
  {
    id: 'user-ahmed',
    accountType: 'SmallBusiness',
    role: 'User',
    email: 'finance@ahmedstudio.co',
    phone: '+20 100 482 1190',
    country: 'Egypt',
    trustScore: 60,
    status: 'Active',
    createdAt: now,
    smallBusinessProfile: {
      businessName: 'Ahmed Studio',
      registrationNumber: 'EG-C-204188',
      businessBankAccountName: 'Ahmed Studio LLC',
      businessBankAccountLast4: '4481',
    },
  },
  {
    id: 'user-sara',
    accountType: 'Freelancer',
    role: 'User',
    email: 'sara@saradesigns.co',
    phone: '+20 111 624 3017',
    country: 'Egypt',
    trustScore: 55,
    status: 'Active',
    createdAt: now,
    freelancerProfile: {
      fullName: 'Sara Designs',
      personalBankAccountName: 'Sara Mahmoud',
      personalBankAccountLast4: '1190',
    },
  },
  {
    id: 'user-laila',
    accountType: 'Freelancer',
    role: 'User',
    email: 'laila@independentux.co',
    phone: '+20 122 815 4092',
    country: 'Egypt',
    trustScore: 42,
    status: 'Active',
    createdAt: now,
    freelancerProfile: {
      fullName: 'Laila UX',
      personalBankAccountName: 'Laila Hassan',
      personalBankAccountLast4: '8824',
    },
  },
  {
    id: 'user-admin',
    accountType: 'SmallBusiness',
    role: 'Admin',
    email: 'review@hassil.co',
    phone: '+971 55 438 9021',
    country: 'UAE',
    trustScore: 100,
    status: 'Active',
    createdAt: now,
    smallBusinessProfile: {
      businessName: 'Hassil Admin',
      registrationNumber: 'HASSIL-SBX',
      businessBankAccountName: 'Hassil Review Desk',
      businessBankAccountLast4: '0001',
    },
  },
];

const completedFactoringInvoice: Invoice = {
  id: 'inv-ahmed-paid',
  userId: 'user-ahmed',
  clientId: 'client-omar',
  client: clients[0],
  invoiceNumber: 'AHM-2026-014',
  receivableSource: 'DirectClientInvoice',
  amount: 20000,
  currency: 'USD',
  issueDate: '2026-03-01',
  dueDate: '2026-04-20',
  description: 'Brand identity and launch assets delivered to Omar Hospitality Group.',
  paymentTerms: 'Net 45',
  status: 'Paid',
  fingerprint: createFingerprint('AHM-2026-014', clients[0].email, 20000, '2026-04-20', 'DirectClientInvoice'),
  createdAt: '2026-03-01T09:00:00+03:00',
  documents: [
    { id: 'doc-ahmed-paid-1', invoiceId: 'inv-ahmed-paid', fileName: 'signed-delivery-note.pdf', documentType: 'Delivery Proof', uploadedAt: '2026-03-01T09:15:00+03:00' },
  ],
  clientConfirmation: {
    id: 'conf-ahmed-paid',
    invoiceId: 'inv-ahmed-paid',
    token: 'paid-factoring-token',
    clientEmail: clients[0].email,
    status: 'Confirmed',
    clientNote: 'Work received and approved.',
    respondedAt: '2026-03-02T12:00:00+03:00',
    expiresAt: '2026-03-08T12:00:00+03:00',
  },
  advanceRequestId: 'adv-ahmed-paid',
};

const completedDiscountingInvoice: Invoice = {
  id: 'inv-sara-paid',
  userId: 'user-sara',
  clientId: 'client-platform',
  client: clients[2],
  invoiceNumber: 'SAR-2026-021',
  receivableSource: 'FreelancePlatformPayout',
  amount: 800,
  currency: 'USD',
  issueDate: '2026-03-12',
  dueDate: '2026-04-10',
  description: 'Landing page design payout approved by marketplace client.',
  paymentTerms: 'Platform payout hold',
  status: 'Paid',
  fingerprint: createFingerprint('SAR-2026-021', clients[2].email, 800, '2026-04-10', 'FreelancePlatformPayout'),
  createdAt: '2026-03-12T10:00:00+03:00',
  documents: [
    { id: 'doc-sara-paid-1', invoiceId: 'inv-sara-paid', fileName: 'platform-payout-proof.png', documentType: 'Platform Payout Proof', uploadedAt: '2026-03-12T10:15:00+03:00' },
  ],
  advanceRequestId: 'adv-sara-paid',
};

const liveFactoringInvoice: Invoice = {
  id: 'inv-ahmed-live',
  userId: 'user-ahmed',
  clientId: 'client-noura',
  client: clients[1],
  invoiceNumber: 'AHM-2026-018',
  receivableSource: 'DirectClientInvoice',
  amount: 18000,
  currency: 'USD',
  issueDate: '2026-04-25',
  dueDate: '2026-06-09',
  description: 'Ramadan merchandising package and campaign visuals delivered.',
  paymentTerms: 'Net 45',
  status: 'Submitted',
  fingerprint: createFingerprint('AHM-2026-018', clients[1].email, 18000, '2026-06-09', 'DirectClientInvoice'),
  createdAt: '2026-04-25T11:00:00+03:00',
  documents: [
    { id: 'doc-ahmed-live-1', invoiceId: 'inv-ahmed-live', fileName: 'client-po-and-delivery-note.pdf', documentType: 'Purchase Order', uploadedAt: '2026-04-25T11:10:00+03:00' },
  ],
};

const liveDiscountingInvoice: Invoice = {
  id: 'inv-sara-live',
  userId: 'user-sara',
  clientId: 'client-lynx',
  client: clients[3],
  invoiceNumber: 'SAR-2026-027',
  receivableSource: 'DirectClientInvoice',
  amount: 2200,
  currency: 'USD',
  issueDate: '2026-04-24',
  dueDate: '2026-05-29',
  description: 'Product design sprint and landing page refresh.',
  paymentTerms: 'Net 35',
  status: 'Submitted',
  fingerprint: createFingerprint('SAR-2026-027', clients[3].email, 2200, '2026-05-29', 'DirectClientInvoice'),
  createdAt: '2026-04-24T14:00:00+03:00',
  documents: [
    { id: 'doc-sara-live-1', invoiceId: 'inv-sara-live', fileName: 'signed-sow.pdf', documentType: 'Signed SOW', uploadedAt: '2026-04-24T14:15:00+03:00' },
  ],
};

const reviewInvoice: Invoice = {
  id: 'inv-review-1',
  userId: 'user-sara',
  clientId: 'client-platform',
  client: clients[2],
  invoiceNumber: 'SAR-2026-028',
  receivableSource: 'FreelancePlatformPayout',
  amount: 2900,
  currency: 'USD',
  issueDate: '2026-04-26',
  dueDate: '2026-06-20',
  description: 'Marketplace payout close to current freelancer limit.',
  paymentTerms: 'Platform payout review',
  status: 'PendingReview',
  fingerprint: createFingerprint('SAR-2026-028', clients[2].email, 2900, '2026-06-20', 'FreelancePlatformPayout'),
  createdAt: '2026-04-26T15:30:00+03:00',
  documents: [],
  advanceRequestId: 'adv-review-1',
};

const expiredConfirmationInvoice: Invoice = {
  id: 'inv-ahmed-expired',
  userId: 'user-ahmed',
  clientId: 'client-noura',
  client: clients[1],
  invoiceNumber: 'AHM-2026-019',
  receivableSource: 'DirectClientInvoice',
  amount: 12400,
  currency: 'USD',
  issueDate: '2026-04-18',
  dueDate: '2026-06-02',
  description: 'Storefront launch assets awaiting client confirmation.',
  paymentTerms: 'Net 45',
  status: 'PendingClientConfirmation',
  fingerprint: createFingerprint('AHM-2026-019', clients[1].email, 12400, '2026-06-02', 'DirectClientInvoice'),
  createdAt: '2026-04-18T10:00:00+03:00',
  documents: [
    { id: 'doc-ahmed-expired-1', invoiceId: 'inv-ahmed-expired', fileName: 'signed-scope.pdf', documentType: 'Signed Contract', uploadedAt: '2026-04-18T10:10:00+03:00' },
  ],
  clientConfirmation: {
    id: 'conf-ahmed-expired',
    invoiceId: 'inv-ahmed-expired',
    token: 'expired-client-token',
    clientEmail: clients[1].email,
    status: 'Pending',
    expiresAt: '2026-04-20T12:00:00+03:00',
  },
  advanceRequestId: 'adv-ahmed-expired',
};

const disputedInvoice: Invoice = {
  id: 'inv-ahmed-disputed',
  userId: 'user-ahmed',
  clientId: 'client-omar',
  client: clients[0],
  invoiceNumber: 'AHM-2026-016',
  receivableSource: 'DirectClientInvoice',
  amount: 7600,
  currency: 'USD',
  issueDate: '2026-03-22',
  dueDate: '2026-05-06',
  description: 'Campaign adaptation invoice disputed by client.',
  paymentTerms: 'Net 45',
  status: 'Disputed',
  fingerprint: createFingerprint('AHM-2026-016', clients[0].email, 7600, '2026-05-06', 'DirectClientInvoice'),
  createdAt: '2026-03-22T09:00:00+03:00',
  documents: [
    { id: 'doc-ahmed-disputed-1', invoiceId: 'inv-ahmed-disputed', fileName: 'delivery-thread.pdf', documentType: 'Delivery Proof', uploadedAt: '2026-03-22T09:15:00+03:00' },
  ],
  clientConfirmation: {
    id: 'conf-ahmed-disputed',
    invoiceId: 'inv-ahmed-disputed',
    token: 'disputed-client-token',
    clientEmail: clients[0].email,
    status: 'Disputed',
    clientNote: 'Final files did not match the approved scope.',
    respondedAt: '2026-03-23T13:20:00+03:00',
    expiresAt: '2026-03-29T13:20:00+03:00',
  },
  advanceRequestId: 'adv-ahmed-disputed',
};

const approvedDiscountingInvoice: Invoice = {
  id: 'inv-sara-approved',
  userId: 'user-sara',
  clientId: 'client-lynx',
  client: clients[3],
  invoiceNumber: 'SAR-2026-029',
  receivableSource: 'DirectClientInvoice',
  amount: 1400,
  currency: 'USD',
  issueDate: '2026-04-27',
  dueDate: '2026-05-27',
  description: 'Design QA retainer approved for advance.',
  paymentTerms: 'Net 30',
  status: 'Approved',
  fingerprint: createFingerprint('SAR-2026-029', clients[3].email, 1400, '2026-05-27', 'DirectClientInvoice'),
  createdAt: '2026-04-27T11:00:00+03:00',
  documents: [
    { id: 'doc-sara-approved-1', invoiceId: 'inv-sara-approved', fileName: 'signed-retainer.pdf', documentType: 'Signed Contract', uploadedAt: '2026-04-27T11:10:00+03:00' },
  ],
  advanceRequestId: 'adv-sara-approved',
};

const invoices: Invoice[] = [
  completedFactoringInvoice,
  completedDiscountingInvoice,
  liveFactoringInvoice,
  liveDiscountingInvoice,
  reviewInvoice,
  expiredConfirmationInvoice,
  disputedInvoice,
  approvedDiscountingInvoice,
];

const advances: AdvanceRequest[] = [
  {
    id: 'adv-ahmed-paid',
    invoiceId: 'inv-ahmed-paid',
    userId: 'user-ahmed',
    financingModel: 'InvoiceFactoring',
    repaymentParty: 'Client',
    clientNotificationRequired: true,
    requestedPercent: 0.9,
    advanceAmount: 18000,
    feeRate: 0.02,
    feeAmount: 400,
    settlementBufferAmount: 1600,
    expectedRepaymentAmount: 20000,
    reviewScore: 92,
    approvalMode: 'Auto',
    status: 'Repaid',
    termsAcceptedAt: '2026-03-01T09:20:00+03:00',
    createdAt: '2026-03-01T09:20:00+03:00',
    updatedAt: '2026-04-20T14:00:00+03:00',
  },
  {
    id: 'adv-sara-paid',
    invoiceId: 'inv-sara-paid',
    userId: 'user-sara',
    financingModel: 'InvoiceDiscounting',
    repaymentParty: 'User',
    clientNotificationRequired: false,
    requestedPercent: 0.8,
    advanceAmount: 640,
    feeRate: 0.04,
    feeAmount: 32,
    settlementBufferAmount: 0,
    expectedRepaymentAmount: 672,
    reviewScore: 86,
    approvalMode: 'Auto',
    status: 'Repaid',
    termsAcceptedAt: '2026-03-12T10:20:00+03:00',
    createdAt: '2026-03-12T10:20:00+03:00',
    updatedAt: '2026-04-10T16:00:00+03:00',
  },
  {
    id: 'adv-review-1',
    invoiceId: 'inv-review-1',
    userId: 'user-sara',
    financingModel: 'InvoiceDiscounting',
    repaymentParty: 'User',
    clientNotificationRequired: false,
    requestedPercent: 0.8,
    advanceAmount: 2320,
    feeRate: 0.035,
    feeAmount: 101.5,
    settlementBufferAmount: 0,
    expectedRepaymentAmount: 2421.5,
    reviewScore: 65,
    approvalMode: 'Manual',
    status: 'PendingReview',
    termsAcceptedAt: '2026-04-26T15:45:00+03:00',
    createdAt: '2026-04-26T15:45:00+03:00',
    updatedAt: '2026-04-26T15:45:00+03:00',
  },
  {
    id: 'adv-ahmed-expired',
    invoiceId: 'inv-ahmed-expired',
    userId: 'user-ahmed',
    financingModel: 'InvoiceFactoring',
    repaymentParty: 'Client',
    clientNotificationRequired: true,
    requestedPercent: 0.9,
    advanceAmount: 11160,
    feeRate: 0.02,
    feeAmount: 248,
    settlementBufferAmount: 992,
    expectedRepaymentAmount: 12400,
    reviewScore: 55,
    approvalMode: 'Manual',
    status: 'PendingClientConfirmation',
    termsAcceptedAt: '2026-04-18T10:20:00+03:00',
    createdAt: '2026-04-18T10:20:00+03:00',
    updatedAt: '2026-04-18T10:20:00+03:00',
  },
  {
    id: 'adv-ahmed-disputed',
    invoiceId: 'inv-ahmed-disputed',
    userId: 'user-ahmed',
    financingModel: 'InvoiceFactoring',
    repaymentParty: 'Client',
    clientNotificationRequired: true,
    requestedPercent: 0.9,
    advanceAmount: 6840,
    feeRate: 0.02,
    feeAmount: 152,
    settlementBufferAmount: 608,
    expectedRepaymentAmount: 7600,
    reviewScore: 10,
    approvalMode: 'Manual',
    status: 'Rejected',
    rejectionReason: 'Client disputed invoice scope.',
    termsAcceptedAt: '2026-03-22T09:25:00+03:00',
    createdAt: '2026-03-22T09:25:00+03:00',
    updatedAt: '2026-03-23T13:20:00+03:00',
  },
  {
    id: 'adv-sara-approved',
    invoiceId: 'inv-sara-approved',
    userId: 'user-sara',
    financingModel: 'InvoiceDiscounting',
    repaymentParty: 'User',
    clientNotificationRequired: false,
    requestedPercent: 0.8,
    advanceAmount: 1120,
    feeRate: 0.035,
    feeAmount: 49,
    settlementBufferAmount: 0,
    expectedRepaymentAmount: 1169,
    reviewScore: 82,
    approvalMode: 'Auto',
    status: 'Approved',
    termsAcceptedAt: '2026-04-27T11:20:00+03:00',
    createdAt: '2026-04-27T11:20:00+03:00',
    updatedAt: '2026-04-27T11:20:00+03:00',
  },
];

const transactions: Transaction[] = [
  { id: 'tx-a1', userId: 'user-ahmed', invoiceId: 'inv-ahmed-paid', advanceRequestId: 'adv-ahmed-paid', type: 'AdvanceDisbursement', direction: 'Credit', amount: 18000, description: 'Advance sent to Ahmed Studio bank account.', createdAt: '2026-03-02T13:00:00+03:00' },
  { id: 'tx-a2', userId: 'user-ahmed', invoiceId: 'inv-ahmed-paid', advanceRequestId: 'adv-ahmed-paid', type: 'ClientPaymentToHassil', direction: 'Credit', amount: 20000, description: 'Client payment received by Hassil collection account.', createdAt: '2026-04-20T12:00:00+03:00' },
  { id: 'tx-a3', userId: 'user-ahmed', invoiceId: 'inv-ahmed-paid', advanceRequestId: 'adv-ahmed-paid', type: 'PlatformFee', direction: 'Internal', amount: 400, description: 'Fixed upfront fee collected from settlement.', createdAt: '2026-04-20T12:05:00+03:00' },
  { id: 'tx-a4', userId: 'user-ahmed', invoiceId: 'inv-ahmed-paid', advanceRequestId: 'adv-ahmed-paid', type: 'BufferRelease', direction: 'Credit', amount: 1600, description: 'Remaining settlement buffer released to Ahmed Studio.', createdAt: '2026-04-20T12:15:00+03:00' },
  { id: 'tx-s1', userId: 'user-sara', invoiceId: 'inv-sara-paid', advanceRequestId: 'adv-sara-paid', type: 'AdvanceDisbursement', direction: 'Credit', amount: 640, description: 'Advance sent to Sara Designs.', createdAt: '2026-03-12T11:00:00+03:00' },
  { id: 'tx-s2', userId: 'user-sara', invoiceId: 'inv-sara-paid', advanceRequestId: 'adv-sara-paid', type: 'DetectedIncomingPayment', direction: 'Internal', amount: 800, description: 'Platform payout detected in Sara account.', createdAt: '2026-04-10T15:40:00+03:00' },
  { id: 'tx-s3', userId: 'user-sara', invoiceId: 'inv-sara-paid', advanceRequestId: 'adv-sara-paid', type: 'UserRepayment', direction: 'Debit', amount: 672, description: 'Sara repaid Hassil after receiving the client payment.', createdAt: '2026-04-10T16:00:00+03:00' },
  { id: 'tx-s4', userId: 'user-sara', invoiceId: 'inv-sara-paid', advanceRequestId: 'adv-sara-paid', type: 'PlatformFee', direction: 'Internal', amount: 32, description: 'Fixed upfront fee collected at repayment.', createdAt: '2026-04-10T16:01:00+03:00' },
];

const trustScoreEvents: TrustScoreEvent[] = [
  { id: 'score-a1', userId: 'user-ahmed', oldScore: 50, newScore: 55, reason: 'Client confirmed a factoring invoice.', createdAt: '2026-03-02T12:00:00+03:00' },
  { id: 'score-a2', userId: 'user-ahmed', oldScore: 55, newScore: 60, reason: 'Completed repayment cycle with buffer release.', createdAt: '2026-04-20T12:15:00+03:00' },
  { id: 'score-s1', userId: 'user-sara', oldScore: 45, newScore: 55, reason: 'Repaid discounting advance after client payment detection.', createdAt: '2026-04-10T16:00:00+03:00' },
];

export const initialState: AppState = {
  currentUserId: 'user-ahmed',
  users,
  clients,
  invoices,
  advanceRequests: advances,
  transactions,
  trustScoreEvents,
  aiReviewSnapshots: [
    buildAiSnapshot('adv-review-1', 65, ['Supporting document is missing', 'Invoice is close to current freelancer limit']),
  ],
  adminReviews: [],
  currentPage: 'landing',
  pageParams: {},
  showDemoSwitcher: true,
  toasts: [],
};
